# Generated by Django 6.0.2 on 2026-03-02 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener exactamente 10 dígitos.', regex='^\\d{10}$')])),
                ('Nota', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
